---

- name: check execise 1.2
  shell: "ansible node1 -m command -a 'cat /etc/motd'"
  register: result

- name: check result 1.2
  set_fact:
    progress={{ progress_12 }}
  when:
      - result.stdout is search("{{ exe12_msg }}")

#- name: check execise 1.3
#  shell: ""
#  register: result

- name: display progress
  debug: msg={{ progress }}
